In [1]:
import numpy as np
import pandas as pd

df_countries = pd.read_csv('math_statistics_py/statistics/dados_1997_2011_paises_csv.csv', sep=';', encoding='latin1', decimal=',')

df_countries

,pais,ano,idh,corrupcao_indice,competitividade_indice,globalizacao_indice,pib,populacao
0,África do Sul,1997,0.6328,56,44.54,52.60298,1.488142e+08,43353.63200
1,África do Sul,1998,0.6272,57,31.11,54.51911,1.342956e+08,43961.92400
2,África do Sul,1999,0.6216,50,43.90,61.04379,1.331836e+08,44526.27200
3,África do Sul,2000,0.6160,52,51.52,62.47182,1.328776e+08,45064.09800
4,África do Sul,2001,0.6126,50,45.12,62.04144,1.184790e+08,45576.21500
...,...,...,...,...,...,...,...,...
280,Reino Unido,2007,0.8560,86,75.45,82.12010,1.448770e+06,61337.36992
281,Reino Unido,2008,0.8600,86,71.90,81.67998,1.447825e+06,61731.27576
282,Reino Unido,2009,0.8600,84,76.07,79.31000,1.377247e+06,62086.03336
283,Reino Unido,2010,0.8620,77,76.81,80.18000,1.395893e+06,62438.13815
284,Reino Unido,2011,0.8630,77,80.28,81.68000,1.500045e+06,62262.00000

In [2]:
df_countries.groupby('pais').agg(num = pd.NamedAgg('pais', 'count')).reset_index()

              pais  num
0         Alemanha   15
1        Austrália   15
2           Brasil   15
3          Bélgica   15
4           Canadá   15
5            China   15
6        Cingapura   15
7           Coréia   15
8          Espanha   15
9   Estados Unidos   15
10          França   15
11         Holanda   15
12          Itália   15
13           Japão   15
14          México   15
15     Reino Unido   15
16          Rússia   15
17   África do Sul   15
18           Índia   15

In [3]:
df_countries.dtypes

pais                       object
ano                         int64
idh                       float64
corrupcao_indice            int64
competitividade_indice    float64
globalizacao_indice       float64
pib                       float64
populacao                 float64
dtype: object

## Análises e funções python

| análises | funções |
|----------|---------|
| Mínimo, Máximo, Média | min(), max(), mean() |
| Moda | mode() |
| Mediana | median() |
| Quartis, Percentis | quantile() |
| Desvio medio absoluto | mad() |
| Variância, Desvio Padrão | var(), std() |
| Contagem | count() |

In [4]:
df_countries.groupby('pais')['idh'].apply(lambda x: x.mode().iloc[0]).to_frame().reset_index()

              pais     idh
0         Alemanha  0.8466
1        Austrália  0.8958
2           Brasil  0.6464
3          Bélgica  0.8628
4           Canadá  0.9030
5            China  0.5598
6        Cingapura  0.7404
7           Coréia  0.8078
8          Espanha  0.8162
9   Estados Unidos  0.8886
10          França  0.8298
11         Holanda  0.8724
12          Itália  0.8070
13           Japão  0.8572
14          México  0.6916
15     Reino Unido  0.8600
16          Rússia  0.6814
17   África do Sul  0.5990
18           Índia  0.4466

In [5]:
df_countries.groupby('pais')['idh'].apply(lambda x: x.quantile([0.05,0.25,0.5,0.75,0.95])).to_frame().reset_index().rename(columns={'level_1': 'percentil'})

        pais  percentil      idh
0   Alemanha       0.05  0.85066
1   Alemanha       0.25  0.86710
2   Alemanha       0.50  0.88880
3   Alemanha       0.75  0.90050
4   Alemanha       0.95  0.90360
..       ...        ...      ...
90     Índia       0.05  0.44996
91     Índia       0.25  0.46530
92     Índia       0.50  0.49540
93     Índia       0.75  0.52500
94     Índia       0.95  0.54350

[95 rows x 3 columns]

In [12]:
df_countries.groupby('pais').agg(desvio_medio_abs_idh = pd.NamedAgg( column='idh', aggfunc=lambda x: x.mad())).reset_index()

AttributeError: 'Series' object has no attribute 'mad'

In [13]:
df_countries.groupby('pais').agg(variancia_idh = pd.NamedAgg('idh', 'var'),
dp_idh = pd.NamedAgg('idh', 'std')).reset_index()

              pais  variancia_idh    dp_idh
0         Alemanha       0.000408  0.020187
1        Austrália       0.000110  0.010485
2           Brasil       0.000517  0.022727
3          Bélgica       0.000041  0.006401
4           Canadá       0.000142  0.011899
5            China       0.001758  0.041928
6        Cingapura       0.001443  0.037984
7           Coréia       0.000886  0.029773
8          Espanha       0.000372  0.019299
9   Estados Unidos       0.000043  0.006558
10          França       0.000328  0.018103
11         Holanda       0.000152  0.012341
12          Itália       0.000563  0.023729
13           Japão       0.000213  0.014602
14          México       0.000607  0.024646
15     Reino Unido       0.000189  0.013745
16          Rússia       0.000698  0.026420
17   África do Sul       0.000096  0.009790
18           Índia       0.001185  0.034417